teams:
- id: 1
  name: 'GOC'
  min_players: 1
  spawn_chance: 100
  spawn_conditions:
    spawn_wave: 'NtfWave'
    spawn_position:
      x: 0
      y: 0
      z: 0
    used_item: 'None'
    target_scp: 'None'
    spawn_delay: 0
  cassie_message: 'team arrived'
  cassie_translation: 'Team arrived!'
  is_noisy: true
  sound_path: '/path/to/your/ogg/file'
  sound_volume: 1
  TEST: 123
  team_alive_to_win: []
  roles:
  -
    max_players: 1
    priority: First
    id: 1
    name: 'Janitor'
    override_role_name: false
    nickname: 'D-%dnumber%'
    custom_info: 'Janitor'
    badge_name: 'Janitor'
    badge_color: 'pumpkin'
    role: ClassD
    team: ClassD
    role_appearance: ClassD
    is_friend_of: []
    health:
      amount: 100
      maximum: 100
      hume_shield: 0
      hume_shield_regeneration_amount: 2
      hume_shield_regeneration_delay: 7.5
    ahp:
      amount: 0
      limit: 75
      decay: 1.20000005
      efficacy: 0.699999988
      sustain: 0
      persistant: false
    effects: []
    stamina:
      regen_multiplier: 1
      usage_multiplier: 1
      infinite: false
    max_scp330_candies: 2
    can_escape: false
    role_after_escape: 
    scale:
      x: 1
      y: 1
      z: 1
    spawn_broadcast: |-
      You are a <color=orange><b>Janitor</b></color>!
      Clean the Light Containment Zone!
    spawn_broadcast_duration: 5
    spawn_hint: 'This hint will be shown when you will spawn as a Janitor!'
    spawn_hint_duration: 5
    custom_inventory_limits:
      Medical: 2
    inventory:
    - Flashlight
    - KeycardJanitor
    custom_items_inventory: []
    ammo:
      Nato9: 10
    damage_multiplier: 1
    spawn_settings: 
    custom_flags: 
    ignore_spawn_system: false
  -
    max_players: 1
    priority: Second
    id: 2
    name: 'Janitor'
    override_role_name: false
    nickname: 'D-%dnumber%'
    custom_info: 'Janitor'
    badge_name: 'Janitor'
    badge_color: 'pumpkin'
    role: ClassD
    team: ClassD
    role_appearance: ClassD
    is_friend_of: []
    health:
      amount: 100
      maximum: 100
      hume_shield: 0
      hume_shield_regeneration_amount: 2
      hume_shield_regeneration_delay: 7.5
    ahp:
      amount: 0
      limit: 75
      decay: 1.20000005
      efficacy: 0.699999988
      sustain: 0
      persistant: false
    effects: []
    stamina:
      regen_multiplier: 1
      usage_multiplier: 1
      infinite: false
    max_scp330_candies: 2
    can_escape: false
    role_after_escape: 
    scale:
      x: 1
      y: 1
      z: 1
    spawn_broadcast: |-
      You are a <color=orange><b>Janitor</b></color>!
      Clean the Light Containment Zone!
    spawn_broadcast_duration: 5
    spawn_hint: 'This hint will be shown when you will spawn as a Janitor!'
    spawn_hint_duration: 5
    custom_inventory_limits:
      Medical: 2
    inventory:
    - Flashlight
    - KeycardJanitor
    custom_items_inventory: []
    ammo:
      Nato9: 10
    damage_multiplier: 1
    spawn_settings: 
    custom_flags: 
    ignore_spawn_system: false
